[package]
name = "grpc"
description = "Binary module that adds some extra functions to the gmod"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
rglua = "3.0.0-beta2"
discord-rich-presence = "0.2.*"
once_cell = "1.19.0"
